export const testIds = {
  input: 'todo-input',
  addButton: 'todo-add-button',
  list: 'todo-list',
  item: 'todo-item',
  itemText: 'todo-item-text',
  itemTimestamp: 'todo-item-timestamp',
  itemToggle: 'todo-item-toggle',
  itemDeleteButton: 'todo-item-delete-button',
  confirmDialog: 'todo-confirm-dialog',
  confirmButton: 'todo-confirm-button',
  cancelButton: 'todo-cancel-button',
  filterAll: 'todo-filter-all',
  filterActive: 'todo-filter-active',
  filterDone: 'todo-filter-done',
}
